// Code generated by goctl. DO NOT EDIT.
package types

type PingRes struct {
	Msg string `json:"msg"`
}

type Token struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
}

type RegisterReq struct {
	Name              string `json:"name" validate:"required"`
	RankMasterAccount string `json:"rank_master_account" validate:"required"`
	Mobile            string `json:"mobile" validate:"required,len=11,numeric"`
	Avatar            string `json:"avatar" validate:"required"`
	Email             string `json:"email" validate:"required,email"`
	Code              string `json:"code" validate:"required"`
	Password          string `json:"password" validate:"required"`
}

type RegisterRes struct {
	UserId string `json:"user_id"`
	Token  Token  `json:"token"`
}

type LoginReq struct {
	RankMasterAccount string `json:"rank_master_account" validate:"required"`
	Password          string `json:"password" validate:"required"`
}

type LoginRes struct {
	UserId string `json:"user_id"`
	Token  Token  `json:"token"`
}

type GetEmailCodeReq struct {
	Email string `json:"email" validate:"required,email"`
}

type GetEmailCodeRes struct {
}
