// Code generated by goctl. DO NOT EDIT.
package types

type PingRes struct {
	Msg string `json:"msg"`
}

type Token struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
}

type RegisterReq struct {
	Name              string `json:"name" validate:"required"`                  // 昵称
	RankMasterAccount string `json:"rank_master_account" validate:"required"`   // RankMaster账号
	Mobile            string `json:"mobile" validate:"required,len=11,numeric"` // 手机号
	Avatar            string `json:"avatar" validate:"required"`                // 头像
	Email             string `json:"email" validate:"required,email"`           // 邮箱
	Code              string `json:"code" validate:"required"`                  // 邮箱验证码
	Password          string `json:"password" validate:"required"`              // 密码
}

type RegisterRes struct {
	UserId string `json:"user_id"` // 用户ID
	Token  Token  `json:"token"`   // token
}

type LoginReq struct {
	RankMasterAccount string `json:"rank_master_account" validate:"required"` // RankMaster账号
	Password          string `json:"password" validate:"required"`            // 密码
}

type LoginRes struct {
	UserId string `json:"user_id"` // 用户ID
	Token  Token  `json:"token"`   // token
}

type GetEmailCodeReq struct {
	Email string `json:"email" validate:"required,email"` // 邮箱
}

type GetEmailCodeRes struct {
}

type GetRankMasterAccountReq struct {
	RankMasterAccount string `path:"rank_master_account" validate:"required"` // RankMaster账号
}

type GetRankMasterAccountRes struct {
}
