version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - rank-master-back

  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass 123456 --appendonly yes
    ports:
      - "6379:6379"

    networks:
      - rank-master-back
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
     - rank-master-back

  kafka:
    image: bitnami/kafka
    container_name: kafka
    restart: always
    privileged: true
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
     - rank-master-back
  rank-master-back:
    image: rank-master-back
    build:
     context: .
     dockerfile: Dockerfile
    container_name: rank-master-back
    ports:
      - "8888:8888"
    depends_on:
      - mysql
      - redis
      - zookeeper
      - kafka

networks:
  rank-master-back:
