// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"rank-master-back/infrastructure/pkg/es"
	"rank-master-back/infrastructure/pkg/mq"
	"rank-master-back/infrastructure/pkg/ormengine"
	"rank-master-back/infrastructure/pkg/rdb"
	"rank-master-back/infrastructure/pkg/uploadfile/oss"
	"rank-master-back/internal/cache"
	"rank-master-back/internal/config"
	"rank-master-back/internal/repository"
	"rank-master-back/internal/svc"
)

import (
	_ "embed"
)

// Injectors from wire.go:

func InitializeServiceContext(c config.Config) (svc.ServiceContext, error) {
	db, err := ormengine.NewGormEngine(c)
	if err != nil {
		return svc.ServiceContext{}, err
	}
	client := rdb.NewRdbClient(c)
	pusher := mq.NewPusher(c)
	esEs, err := es.NewEs(c)
	if err != nil {
		return svc.ServiceContext{}, err
	}
	ossClient, err := oss.NewOssClient(c)
	if err != nil {
		return svc.ServiceContext{}, err
	}
	iTemplate := repository.NewTemplateDao()
	iUserCache := cache.NewUserCache(c)
	iUser := repository.NewUserDao(iUserCache)
	serviceContext := svc.ServiceContext{
		Config:         c,
		DB:             db,
		RDB:            client,
		KqPusherClient: pusher,
		Es:             esEs,
		Oss:            ossClient,
		TemplateDao:    iTemplate,
		UserDao:        iUser,
	}
	return serviceContext, nil
}

// wire.go:

var RepositorySet = wire.NewSet(repository.NewTemplateDao, repository.NewUserDao)

var CacheSet = wire.NewSet(cache.NewUserCache)
