// Code generated by "stringer -type Code -linecomment"; DO NOT EDIT.

package e

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OKCode-200]
	_ = x[ServerErrorCode-500]
	_ = x[ErrRegisterMobileExistCode-2000]
	_ = x[ErrRegisterAccountExistCode-2001]
	_ = x[ErrLoginPasswdCode-1000]
	_ = x[ErrEmailCodeFailCode-3000]
	_ = x[ErrLoginMobileNotExistCode-4000]
}

const (
	_Code_name_0 = "OKCode"
	_Code_name_1 = "ServerErrorCode"
	_Code_name_2 = "password error"
	_Code_name_3 = "mobile already existsaccount already exists"
	_Code_name_4 = "email code error"
	_Code_name_5 = "mobile not exists"
)

var (
	_Code_index_3 = [...]uint8{0, 21, 43}
)

func (i Code) String() string {
	switch {
	case i == 200:
		return _Code_name_0
	case i == 500:
		return _Code_name_1
	case i == 1000:
		return _Code_name_2
	case 2000 <= i && i <= 2001:
		i -= 2000
		return _Code_name_3[_Code_index_3[i]:_Code_index_3[i+1]]
	case i == 3000:
		return _Code_name_4
	case i == 4000:
		return _Code_name_5
	default:
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
