Name: app
Host: 0.0.0.0
Port: 8888
WorkerId: 1
Mode: test
Telemetry:
  Endpoint: http://127.0.0.1:14268/api/traces

Auth:
  AccessSecret: candy_secret
  AccessExpire: 604800
  RefreshSecret: candy
  RefreshExpire: 2592000
  RefreshAfter: 604800

Mysql:
  DataSource: root:123456@tcp(127.0.0.1:3306)/rank_master?charset=utf8mb4&parseTime=True&loc=Local
  MaxIdleConns: 10
  MaxOpenConns: 100
  MaxLifetime: 1h
  SlowThreshold: 200ms

Log:
  ServiceName: "rank-master"
  Mode: "console"
  Encoding: "plain"
  Path: "logs"
  Level: "info"

Email:
  AuthorizationPassword: "QPKTINKYCZORKVOH"

KqPusherConf:
  Brokers:
    - 123.60.171.43:9095
    - 123.60.91.186:9095
    - 123.60.156.103:9095
  Topic: payment-success

KqConsumerConf:
  Name: kqConsumer
  Brokers:
    - 123.60.171.43:9095
    - 123.60.91.186:9095
    - 123.60.156.103:9095
  Group: kqConsumer
  Topic: payment-success
  Offset: last
  Consumers: 8
  Processors: 8
  Username: kafkatest
  Password: dZX61diTKwQHeBL

Es:
  Addresses:
    - http://localhost:9200/
  Username: elastic
  Password: HLmVfh-0Pr*YX5x4JSFl
  MaxRetries: 0
Redis:
  Host: "127.0.0.1:6379"
  Pass: "123456"

UploadFile:
  AliYunOss:
    Endpoint: candy
    AccessKeyId: candy
    AccessKeySecret: candy
    BucketName: candy
  Path: "./upload_file/"