Name: app
Host: 0.0.0.0
Port: 8888
WorkerId: 1

Auth:
  AccessSecret: candy_secret
  AccessExpire: 604800
  RefreshSecret: candy
  RefreshExpire: 2592000
  RefreshAfter: 604800

DataSource: root:123456@tcp(172.21.203.129:3306)/rank_master?charset=utf8mb4&parseTime=True&loc=Local

Log:
  ServiceName: "rank-master"
  Mode: "file"
  Encoding: "json"
  Path: "logs"
  Level: "debug"

Email:
  AuthorizationPassword: "QPKTINKYCZORKVOH"

KqPusherConf:
  Brokers:
    - 127.0.0.1:9092
  Topic: topic-beyond-like

KqConsumerConf:
  Name: article-kq-consumer
  Brokers:
    - 127.0.1:9092
  Group: group-like-count
  Topic: topic-like-count
  Offset: last
  Consumers: 1
  Processors: 1

Es:
  Addresses:
    - http://localhost:9200/
  Username: elastic
  Password: HLmVfh-0Pr*YX5x4JSFl
  MaxRetries: 0

Redis:
  Address: "172.28.176.1:6379"
  Password: "123456"
  DB: 0

UploadFile:
  AliYunOss:
    Endpoint: candy
    AccessKeyId: candy
    AccessKeySecret: candy
    BucketName: candy
  Path: "./upload_file/"