Name: app
Host: 0.0.0.0
Port: 8888

Auth:
  AccessSecret: candy
  AccessExpire: 604800
  RefreshSecret: candy
  RefreshExpire: 2592000
  RefreshAfter: 604800

DataSource: root:123456@tcp(127.0.0.1:3306)/rank_master?charset=utf8mb4&parseTime=True&loc=Local

LogConfig:
  Mode: "console"
  Encoding: "plain"
  Path: "/log/rank-master.log"
  Level: "debug"