// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTemplate = "template"

// Template mapped from table <template>
type Template struct {
	ID        string         `gorm:"column:id;type:varchar(255);primaryKey" json:"id"`
	CreatedAt *time.Time     `gorm:"column:created_at;comment:创建时间" json:"createdAt"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp" json:"-"`
	Function  *string        `gorm:"column:function;type:varchar(255)" json:"function"`
	Type      *string        `gorm:"column:type;type:varchar(255)" json:"type"`
	Topic     *string        `gorm:"column:topic;type:varchar(255)" json:"topic"`
	Content   *string        `gorm:"column:content;type:varchar(255)" json:"content"`
	Version   *string        `gorm:"column:version;type:varchar(255)" json:"version"`
	Remark    *string        `gorm:"column:remark;type:varchar(255)" json:"remark"`
}

// TableName Template's table name
func (*Template) TableName() string {
	return TableNameTemplate
}
